[package]
name = "wasm-tracing"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.100" }
js-sys = "0.3.77"
parking_lot = { version = "0.12.3", features = ["nightly"] }